### ISSUE TITLE
Class selection does not take into account full class name

### ISSUE THREAD

**Issue by rroques** [tanem/css-revealer#3]
Great tool Tane! Using it at work for a new CSS component in the style guide revealed some classes being listed as being used when they do not match the component class name.

There are some case where the class names are not detected properly:

```
<div class="myClassSuffix"></div>
```

will find that `myClass` is present in the class names. 

The regex `isSelectorInString.js` should cater for a pattern like `class="<space or previous opening quotes>myClass<space or closing quotes>`. 

Happy regex ;-)  If I find time I will trow you a PR.

**Comment by tanem** [comment]
Hey Remi, thanks for bringing this to my attention!

I added your failing example into the test fixtures, and made a couple of changes. Does the referenced commit fix things up?

**Comment by rroques** [comment]
Thanks Tane! You might want to add a word break before the class name too to cater for prefixes. Sorry I should have been more specific in the bug description.

```
'class="[^"]*\\b' + sanitise(selector) + '\\b'
```

**Comment by tanem** [comment]
All good :smiley: Oh yep, that's an issue - is the latest commit what you had in mind?

**Comment by tanem** [comment]
@rroques I'll merge this within the next day or two if I don't hear back :wink:

**Comment by rroques** [comment]
Hi Tane, sorry on holiday. Merge the PR! Cheers, Remi

**Comment by tanem** [comment]
All done, thanks @rroques :+1: Enjoy your holiday!
